#!/usr/bin/env python3
"""Generate MANIFEST.md and DEVIATIONS.md from build/build-report.json + curation.json.

Both files are generated, so they cannot drift from what is actually installed.
"""
import json, os, subprocess, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rep = json.load(open(os.path.join(ROOT, "build", "build-report.json")))
src = json.load(open(os.path.join(ROOT, "sources.json")))["sources"]
cur = json.load(open(os.path.join(ROOT, "curation.json")))

def ver(clone, path=None):
    d = os.path.join(ROOT, "upstream", clone)
    sha = subprocess.check_output(["git", "-C", d, "rev-parse", "HEAD"], text=True).strip()
    date = subprocess.check_output(["git", "-C", d, "log", "-1", "--format=%ad", "--date=short"], text=True).strip()
    v = ""
    if path and os.path.exists(os.path.join(d, path)):
        v = json.load(open(os.path.join(d, path))).get("version", "")
    return sha, date, v

# ------------------------------------------------------------------ MANIFEST
ce_sha, ce_date, ce_ver = ver("EveryInc_compound-engineering-plugin", ".claude-plugin/plugin.json")
mp_sha, mp_date, _ = ver("mattpocock_skills")
vc_sha, vc_date, _ = ver("vercel-labs_agent-skills")
tb_sha, tb_date, _ = ver("trailofbits_skills")

m = ["# Upstream manifest", "",
     f"Generated by `scripts/render-docs.py` on {rep['builtOn']}. Do not edit by hand.", "",
     "## Sources", "",
     "| Source | Upstream | Version | Pinned commit | Commit date | License | How it is installed |",
     "| --- | --- | --- | --- | --- | --- | --- |"]
rows = [
    ("Compound Engineering", src["compound-engineering"], ce_ver or "—", ce_sha, ce_date),
    ("Matt Pocock",          src["mattpocock"],           "—",            mp_sha, mp_date),
    ("Vercel Labs",          src["vercel"],               "—",            vc_sha, vc_date),
    ("Trail of Bits",        src["trailofbits"],          "—",            tb_sha, tb_date),
]
how = {"native-plugin": "Upstream marketplace, user scope, unmodified",
       "vendored-skill": "Vendored to `build/skills/`, symlinked into `~/.claude/skills`",
       "forked-local-marketplace": "Forked to `build/marketplace/`, installed as local marketplace `trailofbits-curated`"}
for label, s, v, sha, date in rows:
    m.append(f"| {label} | [{s['repo']}]({s['url']}) | {v} | `{sha[:12]}` | {date} | {s['license']} | {how[s['install']]} |")

m += ["", "## Installed skills", "",
      "| Skill | Source | Class | Domain | Routing metadata changed |",
      "| --- | --- | --- | --- | --- |"]
order = {"OWNER": 0, "PASSIVE": 1, "CONDITIONAL": 2, "MANUAL": 3}
for r in sorted(rep["inventory"], key=lambda r: (r["vendor"], r["name"])):
    m.append(f"| `{r['name']}` | {r['vendor']} | {r['cls']} | {r['domain']} | {'yes' if r['modified'] else 'no'} |")

m += ["", f"Plus the {33} skills of the Compound Engineering plugin, installed unmodified. "
          "`ce-*` skills own the lifecycle phases; the plugin's own descriptions already "
          "disambiguate them from each other.", "",
      "## Deliberately excluded", ""]
for vendor in ("mattpocock", "vercel", "trailofbits"):
    m.append(f"### {vendor}")
    m.append("")
    for what, why in cur[vendor]["excluded"].items():
        m.append(f"- **{what}** — {why}")
    m.append("")
open(os.path.join(ROOT, "MANIFEST.md"), "w").write("\n".join(m))

# ------------------------------------------------------------------ DEVIATIONS
d = ["# Deviations from upstream", "",
     f"Generated by `scripts/render-docs.py` on {rep['builtOn']}. Do not edit by hand — "
     "change `curation.json` and rebuild.", "",
     "Every change this stack makes to an upstream skill is listed here. All of them are "
     "frontmatter-only: `description` and `disable-model-invocation`. No skill body, script, "
     "agent, or hook is modified. Upstream clones under `upstream/` are read-only.", ""]
by_skill = {}
for x in rep["deviations"]:
    by_skill.setdefault((x["vendor"], x["skill"]), []).append(x)
for (vendor, skill), xs in sorted(by_skill.items()):
    d += [f"## `{skill}`  ·  {vendor}  ·  {xs[0]['cls']}", "", f"**Why.** {xs[0]['reason']}", ""]
    for x in xs:
        d += [f"**`{x['key']}`**", "", "_Upstream_", "", "> " + str(x["old"]).replace("\n", " ").strip(), "",
              "_This stack_", "", "> " + str(x["new"]).replace("\n", " ").strip(), ""]
d += ["## Structural deviations", "",
      "- **Trail of Bits plugins are forked, not installed from upstream.** "
      + cur["trailofbits"]["note"], "",
      "- **`evals/` and `tests/` are dropped from the forked Trail of Bits plugins.** "
      "They are upstream CI fixtures, not runtime assets. Nothing in the skills references them.", "",
      "- **Compound Engineering is installed unmodified.** It is the default lifecycle owner, so "
      "its broad triggers are the intended ones, and its skills are already mutually "
      "disambiguated upstream.", ""]
open(os.path.join(ROOT, "DEVIATIONS.md"), "w").write("\n".join(d))
print("wrote MANIFEST.md and DEVIATIONS.md")
