#!/usr/bin/env python3
"""Generate VERIFICATION.md: how each invocation class was tested, and what coverage
each curated skill actually has.

Reads the corpus, the held-out set, and every stored eval result. Coverage is counted
from the case files; observed behaviour is counted from the runs. Generated, so it
cannot drift from the evidence sitting next to it.
"""
import json, os, glob, datetime, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CUR = json.load(open(os.path.join(ROOT, "curation.json")))
REP = json.load(open(os.path.join(ROOT, "build", "build-report.json")))

def cases(path):
    return [json.loads(l) for l in open(path) if l.strip()]

CORPUS = cases(os.path.join(ROOT, "eval", "corpus.jsonl"))
HELD = cases(os.path.join(ROOT, "eval", "heldout.jsonl"))
ALL = CORPUS + HELD

# class per skill, from the curation manifest
cls, source = {}, {}
for r in REP["inventory"]:
    cls[r["name"]] = r["cls"]
    source[r["name"]] = r["vendor"]

# coverage from the case files
req = collections.Counter(); forb = collections.Counter(); allow = collections.Counter()
for c in ALL:
    for s in c.get("require", []): req[s] += 1
    for s in c.get("forbid", []): forb[s] += 1
    for s in c.get("allow", []): allow[s] += 1

# observed behaviour from the two latest full sweeps
fired = collections.Counter(); sessions = 0
for f in ("final-corpus.json", "final-heldout.json", "coverage-gaps.json"):
    p = os.path.join(ROOT, "eval", "results", f)
    if not os.path.exists(p):
        continue
    d = json.load(open(p))
    for r in d["results"]:
        for run in r["runs_detail"]:
            sessions += 1
            for s in run["fired"]:
                fired[s] += 1

def rows(want):
    out = []
    for name in sorted(cls):
        if cls[name] != want:
            continue
        out.append((name, source[name], req[name], forb[name], allow[name], fired[name]))
    return out

L = []
w = L.append
w("# Verification")
w("")
w(f"Generated by `scripts/render-verification.py` on {datetime.date.today().isoformat()}. "
  "Do not edit by hand.")
w("")
w("This records how the consolidation was checked, not what it concluded. For the "
  "findings and the headline numbers see [ROUTING-EVAL.md](ROUTING-EVAL.md).")
w("")
w("## What each invocation class can get wrong")
w("")
w("The four classes fail in different directions, so they are tested differently. A "
  "single pass rate hides all of this, which is why coverage is counted per skill below.")
w("")
w("| Class | The failure it is prone to | What a passing test looks like |")
w("| --- | --- | --- |")
w("| **Owner** | Two owners run the same phase | Exactly one owner in the fired set, every run |")
w("| **Passive** | Fires instead of the owner, or not at all, or crowds a neighbour | Fires *alongside* an owner on its domain, silent on trivial work, and does not displace the specialist next to it |")
w("| **Conditional** | Fires on the neighbour's trigger, or misses its own | Fires on the precondition, silent on the near-miss phrasing |")
w("| **Manual** | Selectable at all | Absent from the model's skill listing |")
w("")
w("## How consolidation was verified")
w("")
w("Consolidation means one owner per phase. Three case shapes test it.")
w("")
w("**Collision cases** are written so two owners *would* both fit. `pr-hides-a-bug` says "
  "\"this branch introduces a bug somewhere, review it and find it\", which is a review "
  "request and a debugging request in one sentence. `take-a-look-at-my-changes` is "
  "ambiguous enough to reach any reviewer. `fallback-secret` sits between debugging, "
  "review, and three security specialists. Each accepts several owners and fails on more "
  "than one.")
w("")
w("**Bare-trigger negatives** use the exact phrasing the excluded competitors advertise. "
  "`review-pr-bare` is the literal words \"review this PR\", which upstream Pocock "
  "`code-review`, Trail of Bits `differential-review`, Cursor `review-and-ship` and the "
  "Vercel pair all claimed before curation. It forbids every one of them.")
w("")
w("**Evidence-gated positives** prove the specialist still arrives when it should. "
  "`review-auth-pr-security` and `ho-refunds-and-cards` both require the review owner "
  "*plus* the security specialist, so narrowing a trigger cannot be mistaken for "
  "silencing it.")
w("")
w("The runner treats two owners in one session as a hard failure and exits non-zero. The "
  "owner set is declared in `eval/run-eval.py`, and skills that are designed to co-run "
  "with an owner, such as `diagnosing-bugs`, are deliberately excluded from it.")
w("")
w("## How passive skills were verified")
w("")
w("Passives are the awkward class. They must fire *with* the owner, never *as* the owner, "
  "and never on work too small to need them. One test cannot show that, so each passive "
  "gets three.")
w("")
w("1. **Does it fire on its domain, with an owner?** `ho-csv-button` requires "
  "`react-best-practices` and accepts `ce-work`. Passing means both appear.")
w("2. **Does it stay silent on trivial work?** `string-typo`, `ho-rename-var` and "
  "`explain-function` forbid every overlay. A passive that fires here is noise.")
w("3. **Does it leave the neighbouring specialist alone?** `ho-focus-rings` requires "
  "`web-design-guidelines` and must not be answered by the React overlay; "
  "`ho-eight-booleans` requires `composition-patterns`.")
w("")
w("Both passive failures found here were caught by test 1 while tests 2 and 3 stayed "
  "green, which is what made them diagnosable: the skills were not over-firing, they were "
  "not firing at all. Both had triggers naming the technology rather than the moment. The "
  "fixes were re-run against all three tests before being kept, and the negative cases "
  "were re-run specifically to prove the widened triggers had not become noisy.")
w("")
w("## Coverage by skill")
w("")
w(f"Counted from `eval/corpus.jsonl` and `eval/heldout.jsonl` ({len(ALL)} cases), with "
  f"fire counts observed across the {sessions} sessions in the two latest sweeps.")
w("")
for c, title, note in (
    ("PASSIVE", "Passive", "Wants a require, several forbids, and a neighbour case."),
    ("CONDITIONAL", "Conditional", "Wants a require on its precondition and a forbid on the near miss."),
    ("MANUAL", "Manual", "Not model-selectable, so a zero fire count is the correct result."),
):
    w(f"### {title}")
    w("")
    w(note)
    w("")
    w("| Skill | Source | Required by | Forbidden by | Allowed in | Times fired |")
    w("| --- | --- | --- | --- | --- | --- |")
    for name, src, r, f_, a, fi in rows(c):
        w(f"| `{name}` | {src} | {r} | {f_} | {a} | {fi} |")
    w("")

uncovered = [n for n in sorted(cls)
             if cls[n] != "MANUAL" and req[n] == 0 and forb[n] == 0 and allow[n] == 0]
w("## Skills with no eval coverage")
w("")
if uncovered:
    w("These are installed and model-selectable but no case names them either way. They are "
      "not known to be wrong; they are untested, which is a different thing and worth "
      "saying out loud.")
    w("")
    for n in uncovered:
        w(f"- `{n}` ({source[n]}, {cls[n]})")
else:
    w("None. Every model-selectable skill is named by at least one case.")
w("")
w("## Re-verifying")
w("")
w("```bash")
w("python3 eval/run-eval.py --runs 2                                  # consolidation + owners")
w("python3 eval/run-eval.py --corpus eval/heldout.jsonl --runs 2      # different wording")
w("python3 eval/run-eval.py --tag collision --runs 3                  # just the deliberate fights")
w("python3 scripts/render-verification.py                             # regenerate this file")
w("```")
w("")
w("After changing any passive skill's description, run its three tests together. Fixing "
  "test 1 by widening a trigger is easy and breaks test 2 quietly.")

open(os.path.join(ROOT, "VERIFICATION.md"), "w").write("\n".join(L) + "\n")
print(f"wrote VERIFICATION.md: {len(ALL)} cases, {sessions} sessions, "
      f"{len(uncovered)} uncovered skills")
